### ISSUE TITLE
Duplicate & Rebase (FR: cherry-pick like command)

### ISSUE THREAD

**Issue by xdBronch** [tim-janik/jj-fzf#4]
hello, hope feature requests are ok :smile:
until jj gets something like `-d` for duplicate https://github.com/martinvonz/jj/issues/3518 it would nice if jj-fzf added a command for this, e.g. duplicate + automatic rebase. maybe duplicate could bring up a new "window" like some of the other commands and have this added there?

**Comment by tim-janik** [comment]
> hello, hope feature requests are ok

Sure ;-)

>  😄 until jj gets something like `-d` for duplicate [martinvonz/jj#3518](https://github.com/martinvonz/jj/issues/3518) it would nice if jj-fzf added a command for this, e.g. duplicate + automatic rebase. maybe duplicate could bring up a new "window" like some of the other commands and have this added there?

jj-fzf only supports duplicating a single revision (and anything else would be much more complicated as it'd involve tracking multiple parents) and it automatically makes the duplicate the new working copy and it jumps to the first entry.

The duplicate being a *new commit and the new working copy* makes it the *first* commit listed by `jj log`, which means you can duplicate + rebase by just hitting: `Alt+U` `Alt+R`

Let me know if that works for you, but basically we have a (two) key combo for duplicate (single revision) + rebase already ;-)

**Comment by xdBronch** [comment]
ah i didnt realize before that it makes the duplicated commit the working copy. maybe not as convenient as cherry-pick but i think thats better than not since its probably easier to find where you previously were compared to finding the newly duplicated commit. thanks ill try it out some more

also, duplicate is on `Alt-U` not `Alt-D` :p

**Comment by tim-janik** [comment]
> also, duplicate is on `Alt-U` not `Alt-D` :p

Right, fixed the comment.
Closing for now, feel free to re-open or file a new issue if something else comes up.

**Comment by tim-janik** [comment]
> until jj gets something like `-d` for duplicate [martinvonz/jj#3518](https://github.com/martinvonz/jj/issues/3518) it would nice if jj-fzf added a command for this, e.g. duplicate + automatic rebase. maybe duplicate could bring up a new "window" like some of the other commands and have this added there?

Note, `jj duplicate -d` is alread in jj HEAD, it is just not released yet.
I've asked if this is going to become a part of `jj rebase` or not, [jj#3518](https://github.com/martinvonz/jj/issues/3518).

Until that is cleared up, a tentative implementation is in the [jj-fzf rebase-duplicate](https://github.com/tim-janik/jj-fzf/tree/rebase-duplicate) branch. It is less useful than a `jj rebase --dupliciate` implementation would be though, since the latter could work for multiple commits. In any case, you can take a peek at the branch and let me know what you think.

**Comment by xdBronch** [comment]
> Note, jj duplicate -d is alread in jj HEAD

:0 not sure how i missed that, i do follow main on jj. thanks for the branch it looks quite nice, ill try it out!

**Comment by tim-janik** [comment]
With [v0.24.0](https://github.com/tim-janik/jj-fzf/releases/tag/v0.24.0), jj-fzf supports duplicate (Alt+D) before rebase (Alt+R). So I'm closing this.
